version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5432:5432"

  payment-service:
    build: ./payment-service
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "50051:50051"

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

  gateway:
    build: ./gateway
    depends_on:
      - payment-service
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - gateway
    ports:
      - "3000:3000"